# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_usermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userManager',
        ),
    ]
